# fly.toml app configuration file generated for quiz-app-be-small-dust-3804 on 2025-04-06T21:12:28+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'quiz-app-be-small-dust-3804'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]

[[services.checks]]
  grace_period = "10s" # time to wait before starting health checks after boot
  interval = "15s"
  timeout = "5s"
  method = "get"
  path = "/api/health"
  protocol = "http"
  restart_limit = 0